### ISSUE TITLE
Inconsistent Readings

### ISSUE THREAD

**Issue by kilabyte** [pimoroni/mcp9600-python#7]
The readings that come back are wildly inconsistent or just not accurate. The range should be between 3 and 8 degrees for both hot and cold but running the example i get this...
<img width="444" alt="Screen Shot 2020-12-22 at 3 58 37 PM" src="https://user-images.githubusercontent.com/487948/102944131-bf35d680-446e-11eb-94cf-7c1c20e22c6f.png">

Any ideas?

**Comment by kilabyte** [comment]
any update on this?

**Comment by kilabyte** [comment]
turns out it is the use of the raspi4 makes it do this. if i run this on a raspi3 then everything runs perfectly

**Comment by TBouvet1** [comment]
I am using a raspi3B+ and (after fixing the baud rate) one of my probes is doing exactly what you are showing.  The other is doing fine.  Did you find a fix?

**Comment by kilabyte** [comment]
The fix was just to use a raspi3B+ and now ive had no issues. haven't gone back to a 4
